### ISSUE TITLE
console.clear() doesn’t work in the Playground (on Chrome)

### ISSUE THREAD

**Issue by rauschma** [babel/babel.github.io#105]
https://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&loose=false&code=console.clear()

I’m getting:

    Uncaught TypeError: Illegal invocation

**Comment by sparty02** [comment]
This is most likely due to the 'capturingConsole' used to grab output and place it into the 'console' div in the REPL.  We'll need to beef up that decorator to support more console methods (it doesn't support anything outside of log right now...i.e. console.error('string') fails with the same error).

**Comment by thejameskyle** [comment]
mm, we should add some more methods and alias the rest of the console methods on the capturing console.

```js
_(console).functions().each(function(name) {
  capturingConsole[name] = function() {
    console[name].apply(console, arguments);
  };
});

capturingConsole.log = ...;
capturingConsole.info = ...;
capturingConsole.assert = ...;
capturingConsole.clear = ...;
```

**Comment by sebmck** [comment]
@thejameskyle Probably best to just alias `error` and `info` to `log`. `console.clear` can be trivially implemented with just `buffer = [];`.

**Comment by thejameskyle** [comment]
yeah that sounds good
