### ISSUE TITLE
Highlighting issue in menu

### ISSUE THREAD

**Issue by xtuc** [babel/babel.github.io#1141]
The issue is in: [header.html](https://github.com/babel/babel.github.io/blob/master/_includes/header.html#L23).

![cbcbb602-d5ba-11e6-86ed-36f8ab11a933](https://cloud.githubusercontent.com/assets/1493671/22011004/ed0b989a-dc8c-11e6-9510-89d456916e7b.png)

The `contains` could be replaced with an startWith or an equal?

**Comment by existentialism** [comment]
If we wind up making contribute top level, the above won't actually happen since it wouldn't match /docs _and_ /docs/contribute.

The other problem is that since we link to babel-register in the main docs menu, it highlights twice, since it's nested under core packages.

![image](https://cloud.githubusercontent.com/assets/56288/22023335/660dd99e-dc8b-11e6-94a0-164578a0cd77.png)

One suggested fix is to move things around to match the nav:

/docs/core-packages/babel-register -> /usage/babel-register
