### ISSUE TITLE
Disable experimental flag on "repl" page

### ISSUE THREAD

**Issue by markelog** [babel/babel.github.io#323]
ES7 features could be pretty cool and having quick community response on them is very valuable.

But static analysis tools like eslint, jscs, jshint now getting issues for supporting those constructions, whereas it seems users that do submit those issues are not fully aware of their statuses.

Which means people start using these syntaxes in production environment. Experimental semantics in production environment might be a very bad thing, for obvious reasons.

To limit this "dangerous" impact, i would like to suggest to disable "experimental" flag by default or remove it entirely from the "repl" page.

**Comment by Dashed** [comment]
> ... it seems users that do submit those issues are not fully aware of their statuses.

I find this very hard to believe.

**Comment by thejameskyle** [comment]
@markelog There is no "experimental" flag anymore in Babel itself, it has been replaced by `--stage=n` option which hopefully conveys it's stability better. We do try our best to [explain this option](http://babeljs.io/docs/usage/experimental/) and its risks.

I do not want to remove the option from the REPL because it frequently gets used in discussions about these new specs. We could turn it off by default though (just change [this](https://github.com/babel/babel.github.io/blob/master/scripts/repl.js#L139) to `false`). 

People using experimental proposals in production environments is definitely a concern for anything before stage 2. I'm interested in any ideas you have to stop that (at least for the people who don't know what they are doing completely).

As for static analysis tools getting requests for support, I don't see the real harm in that. They can get tagged for future releases and tracked that way.

---

@Dashed that was unnecessary to say.

**Comment by bergus** [comment]
Please do disable this by default.
People start playing around, and don't notice any difference between ES6 and experimental ES7 drafts - they take them as given, working, tested, and continue to use them in their actual code. When someone points out that they are not using ES6 syntax they get totally confused.
While I'm not suggesting to remove the option entirely, it should at least be non-selected.

Also it might help to group the features on the main page's "ES2015 and beyond" section by spec/draft stage. I guess most people don't understand what "and beyond" means here, and take all of these to be part of ES6.

**Comment by thejameskyle** [comment]
> People start playing around, and don't notice any difference between ES6 and experimental ES7 drafts - they take them as given, working, tested, and continue to use them in their actual code. When someone points out that they are not using ES6 syntax they get totally confused.

I'm okay turning it off by default, but please don't pretend you can speak for everyone. Especially when you've given nothing to back that up.

**Comment by bergus** [comment]
Yes, I cannot speak for everyone of course, and it might as well be that the majority of developers doesn't notice this problem at all. Yet as one of the main contributors to the ES6 tag on StackOverflow I do regularly see this, e.g. [here](http://stackoverflow.com/a/31116409/1048572) or [there](http://stackoverflow.com/questions/13852852/surely-es6-must-have-a-way-to-merge-two-javascript-objects-together-what-is-it#comment52621847_32372430). I'd estimate class initialisers and decorators are the most common mis-attributed ES7 draft features, as they are heavily used with Angular and React.
Thanks for turning it off!
