### ISSUE TITLE
Loader.eval does not work as advertised

### ISSUE THREAD

**Issue by rafaelkaufmann** [babel/babel.github.io#361]
In the docs (under "Learning ES2015"), it is claimed that `es6-module-loader`'s Loader will give you a sandboxed eval method.

```
// Create execution sandboxes – new Loaders
var loader = new Loader({
  global: fixup(window) // replace ‘console.log’
});
loader.eval("console.log(\"hello world!\");");
```

If you test this, you will get a `TypeError: Object [object Object] has no method 'eval']`.

I understand that providing this is `es6-module-loader`'s responsibility, but the docs should reflect the correct way to obtain this functionality or omit it...

**Comment by hzoo** [comment]
In the docs, right under the code

> Additional polyfill needed
Since Babel defaults to using common.js modules, it does not include the polyfill for the module loader API. Get it here.

> Using Module Loader
In order to use this, you'll need to tell Babel to use the system module formatter. Also be sure to check out System.js

Were you able to try that?

**Comment by rafaelkaufmann** [comment]
Oh, I had to re-read paragraph 2 several times in order to understand it. I will test it tomorrow, and see if using `system` instead of `common` doesn't break the rest of my code. This profusion of module formats is quite confusing.

**Comment by thejameskyle** [comment]
Closing as this should be in the support chat
