### ISSUE TITLE
transform-es3-member-expression-literals doesn't escape 'default' keyword

### ISSUE THREAD

**Issue by SebT** [babel/babel.github.io#611]
This: 
```javascript
var foo = {
  default: true,
  var: true
};
```

Outputs to:
```javascript
var foo = {
  default: true,
  "var": true
};
```

The `default` keyword is not quoted. This makes IE8 whine and nothing else works :(

**Comment by hzoo** [comment]
This is the website repo for docs issues, etc. If you have a bug then report it at https://phabricator.babeljs.io/ otherwise use slack/stackoverflow, etc for support questions.

You are looking for babel-plugin-transform-es3-property-literals https://babeljs.io/docs/plugins/#es3.

`transform-es3-member-expression-literals` is for `a.b -> a['b']`

**Comment by SebT** [comment]
transform-es3-member-expression-literals & transform-es3-member-property-literals ignore `default`. I was going to edit my post as it was incoherent but i see this issue is already on the babel phabricator so I'll just watch it. 

Thanks.

**Comment by loganfsmyth** [comment]
They should work, there is a bug around them for modules: https://phabricator.babeljs.io/T2817 if that is what you are seeing.
