### ISSUE TITLE
babel-cli confusing advise

### ISSUE THREAD

**Issue by Rolograaf** [babel/babel.github.io#650]
On  https://babeljs.io/docs/usage/cli/ 
Note: Since it's generally a bad idea to run Babel globally you may want to uninstall the global copy by running `npm uninstall --global babel-cli.`

After installing `npm install --save-dev babel-cli`

On windows 10 now I get this error running `babel`:
`"The CLI has been moved into the package 'babel-cli'.`

`$ npm install -g babel-cli`

Please make up your mind?
thx
Lourens

**Comment by thejameskyle** [comment]
Clearly you are installing the `babel` package not `babel-cli` as that is where the warning comes from https://github.com/babel/babel/blob/60748578fdbb3b92e7c98594aa8f40edbe421ff7/packages/babel/cli.js#L3

Please [read the README](https://github.com/babel/babel#looking-for-support) before opening issues in the wrong place.
thx
James

**Comment by Rolograaf** [comment]
Please do not put an advise like " Found an issue with the docs? Report it here.(https://github.com/babel/babel.github.io/issues/new)" under the webpage when it is apparently the wrong place?

https://babeljs.io/docs/usage/cli/

**Comment by jmm** [comment]
@thejameskyle Where there's the advice to globally uninstall `babel-cli`, perhaps it'd be a good idea to also include `babel`, since a lot of people will still have that installed from v5. On the CLI Usage page it has the advice to globally uninstall `babel-cli`, but then goes into examples like:

```sh
$ babel script.js
```

So without the more comprehensive instructions you wrote up for the CLI Setup page, some people following the Usage page will end up running the CLI from a global `babel` install (leftover v5 or, as in this case apparently, v6).

Perhaps it'd make sense to consolidate https://babeljs.io/docs/usage/cli/ and https://babeljs.io/docs/setup/#babel_cli?

**Comment by purefan** [comment]
The docs referenced by the commit https://github.com/babel/babel/commit/dbc85cff6988aff1de5e7d931991cbf37546c9df still have examples using `babel` which when run give the same warning from the [original post](https://github.com/babel/babel.github.io/issues/650#issue-123094986).
