### ISSUE TITLE
Manage multiple babel-polyfill imports instead of throwing an exception

### ISSUE THREAD

**Issue by alovicu** [babel/babel.github.io#696]
If a web page includes two (or more) different javascripts and both of them import babel-polyfill, the second one that is executed throws the following exception and stops working:

Uncaught Error: only one instance of babel-polyfill is allowed

In these cases the second instance of polyfill should manage automatically the presence of a previous instance and, ideally, avoid the loading of the rest of the code.

In this way polyfill will be able to support the presence of multiple javascripts, designed to work independently from each other, executed asynchronously, and that have to import polyfill since they cannot assume the presence of a polyfill instance in the host page.

**Comment by loganfsmyth** [comment]
This repository is for website documentation issues, but support queries or feature requests. Please see the Babel readme for our suggested support channels. https://github.com/babel/babel#looking-for-support

The current behavior is expected and on purpose. Having two copies of the polyfill loaded in your application is an indication of a problem in your application configuration, you should only ever have one, because your top-level application is the only think that should be loading a polyfill. I'd be happy to chat on Slack if you have specific questions.
