### ISSUE TITLE
IE8 Support

### ISSUE THREAD

**Issue by thejameskyle** [babel/babel.github.io#74]
6to5 supports IE8 for most things, but our website doesn't and I don't think it would be difficult to.

**Comment by sparty02** [comment]
### Items to address

- [ ] JS
 -  Consider lodash and/or ES5 shims
- [ ] CSS 
  - Bootstrap recomends Respond.js for IE8 (media query polyfill)
- [ ] SVG
  - This might be a little trickier (the 6to5 logo is in SVG)
- [ ] @font-face

**Comment by thejameskyle** [comment]
jQuery needs to be downgraded as well.

**Comment by sparty02** [comment]
@thejameskyle  The caveats docs currently say the following, which makes me wonder how much effort we should put into IE8 support.  I get the impression from the wording that the expectation is more or less to polyfill up to ES5 and watch out for un-workaroundable (prolly not a word) cases like Object.defineProperty.  Thoughts?

## ES5

Since 6to5 assumes that your code will be ran in an ES5 environment it uses ES5
functions. So if you're using an environment that has limited or no support for
ES5 such as lower versions of IE then using the
[es5-shim](https://github.com/es-shims/es5-shim) along with the
[6to5 polyfill](/docs/usage/polyfill) will add support for these methods.

## Internet Explorer

### Classes (10 and below)

If you're inheriting from a class then static properties are inherited from it
via [\_\_proto\_\_](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/proto),
this is widely supported but you may run into problems with much older browsers.

**NOTE:** `__proto__` is not supported on IE <= 10 so static properties
**will not** be inherited. See the
[protoToAssign](/docs/usage/transformers#proto-to-assign) for a possible work around.

### Getters/setters (8 and below)

In IE8 `Object.defineProperty` can only be used on DOM objects. This is
unfortunate as it's required to set getters and setters. Due to this if
you plan on supporting IE8 or below then the usage of getters and setters
isn't recommended.

**Reference**: [MDN](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Internet_Explorer_8_specific_notes).

**Comment by thejameskyle** [comment]
There isn't a whole lot to do in order to add IE8 support, it's also the one place online that is guaranteed to have up to date version of 6to5 to use the REPL with for testing. I think it's worth doing.

**Comment by sebmck** [comment]
IE8 sucks eggs.
