### ISSUE TITLE
Remove code of conduct.

### ISSUE THREAD

**Issue by jamesdwilson** [babel/babel.github.io#743]
It is divisive and not helpful.
Suggest adopting NCoC.

**Comment by loganfsmyth** [comment]
I'm not sure what we would gain from this. If the presence of a code of conduct is something you see as a problem, this probably isn't the project for you.

**Comment by jamesdwilson** [comment]
It stifles political speech outside of the context of the project.



As a tool for Social Justice, it recognizes no boundaries between project,
person, and politics. This attitude is written into the Contributor
Covenant with the text, “This Code of Conduct applies both within project
spaces and in public spaces when an individual is representing the project
or its community.” So, when is a project participant not representing the
project? The answer appears to be “never.”

That is, a project participant is always representative of the project. We
can see one example of this from the “Opalgate” incident. In reference to a
Twitter conversation where Opal is not the subject, Ehmke opens an Opal
project issue, and then attempts (with a Social Justice mob of backers) to
intimidate the project managers into removing one of the Twitter
conversants from the project because of his non-project-related speech.


www.breitbart.com/tech/2016/02/25/github-hires-notorious-social-justice-warrior-to-work-on-anti-harassment/

On Wed, Mar 2, 2016 at 3:29 PM, Logan Smyth <notifications@github.com>
wrote:

> I'm not sure what we would gain from this. If the presence of a code of
> conduct is something you see as a problem, this probably isn't the project
> for you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/babel/babel.github.io/issues/743#issuecomment-191440875>
> .
>



-- 
Thank you,

James D. Wilson
http://jameswilson.name
http://lnked.in/technologist
https://github.com/jamesdwilson
*https://twitter.com/thejamesdwilson <https://twitter.com/thejamesdwilson>*

**Comment by gaearon** [comment]
I would like to acknowledge that what you propose is not going to make the topic any less divisive. The reason it is divisive is precisely because people have different opinions about this, and every team of maintainers needs to choose their stance on this issue.

Personally, I find it helpful to compare GitHub communities to other professional environments. For me, the closest analog is working in a company. 

If a coworker of mine makes, say, racist or sexist remarks outside the office space, I’m still going to bring it up with the HR no matter where they did it. In this case, my conclusion would be that their behavior and attitude are harmful to the people I care about and the company environment even though technically they might not doing it “at work”. Because I see GitHub as a professional environment like a company, I don’t see why GitHub projects should be any different.

Ultimately I am not the maintainer, and it is not for me to decide. I am only suggesting you to consider that there are different perspectives on this issue that may not necessarily match yours.

**Comment by kittens** [comment]
Firstly, this is the wrong repo. I assume you opened this issue here because we've closed issues on the `babel/babel` repo in favor of Phabricator. Not sure why you decided to open it on the website repo though.

Secondly, the line you referenced isn't even in the version of the contributor covenant that we use. I only just noticed we're using an older version and I would unequivocally be in favor of upgrading to the latest with the wording you find problematic.

Thirdly, we will not be removing our code of conduct. I'm sorry if this leads to you not helping on issues, contributing code or reporting bugs, since it doesn't appear you have done any of those so far.
