### ISSUE TITLE
FR: Resizable console and error divs.

### ISSUE THREAD

**Issue by hemanth** [babel/babel.github.io#90]
It would be easier to read them, when they are more than a line.

//cc @thejameskyle

**Comment by sparty02** [comment]
@hemanth FWIW, I initially thought this too.  Actually, I didn't even realize that console output was 'printing' on the bottom right and was using the browser console to view output.....until I looked at the source and saw that it was doing something with console.log :confused: 

However, the console and error reporter divs do 'responsively' grow/shrink based on their content, so that's kinda nice....

Were you thinking something frameish where you would drag to resize each reporter div to your liking?  I'm torn on the line between prescribed UX and user customization....

**Comment by thejameskyle** [comment]
:+1: I'd like to see this. jsbin has some really nice ones ([although the code is a bit ugly](https://github.com/jsbin/jsbin/blob/e6712649e90e84cf54423b3495d6baa2c4fe489a/public/js/chrome/splitter.js))
