### ISSUE TITLE
What's the procedure for targeting Chrome only?

### ISSUE THREAD

**Issue by dukedougal** [babel/babel.github.io#910]
I am writing an Electron application. Electron is using Chrome 52.

As I understand it, there are many ES2015 features implemented directly in current Chrome versions.

So it seems to make sense that my application might be faster if I configure Babel to use Chrome's native ES2015 functionality.

Is this documented anywhere?

**Comment by brigand** [comment]
@dukedougal I don't think there's currently a first party preset for that, but you can find some options googling "babel preset chrome".

I don't know that it'll be faster since es6 features are new and they haven't had much time to optimize them. It will result in moderately smaller bundles.

**Comment by hzoo** [comment]
Yep I see another tweet/issue about it every week now https://twitter.com/left_pad/status/770967998291185664 - https://github.com/babel/babel-preset-env which isn't ready yet.

Like mentioned ^, it actually might be slower in certain cases because they haven't had time to optimize. It is definitely something we can work on though and we would appreciate the help on the preset.
